### ISSUE TITLE
Leveraging Open Collective and FundOSS

### ISSUE THREAD

**Issue by gusaus** [opensourcepledge/osspledge.com#89]
Following up on discussions over Twitter and Discord, I wanted to elaborate on how participants in the Open Source Pledge can significantly enhance the impact of their pledges by leveraging the [Open Collective platform](https://opencollective.com/) and the [FundOSS](https://opencollective.com/fundoss) funding initiative.

Not sure if I should detail a proposal here or just link to the draft in progress:
[Leveraging Open Collective Funds and FundOSS to Amplify Open Source Pledge Contributions](https://docs.google.com/document/d/1nWgnFmW-rN2BbfMcwiCi-P-k3C_h7cW7A7TkhFWjLhE/edit?usp=sharing)

Looking forward to hearing questions and requests for clarity in the doc or comments.

**Comment by vladh** [comment]
Thanks for your interest, and for introducing us to [Quadratic Funding](https://www.wtfisqf.com/). I don't think QF is right for us, for a few reasons:

* The point of the Open Source Pledge is for _companies_ to donate, because they (a) have the most reason to do so, as beneficiaries of Open Source software, and (b) can afford to do so. Using QF would mean we would depend on donations from end-users as well for our system to work, and that's not fair to end-users.
* QF seems to work best at scale, when you have a large enough sample of donations to get a sufficient number of “votes” for every potential beneficiary. In our case, this would slow things down to the point where companies would have to wait for a sufficient number of community donations before they can make donations to many maintainers, which is an unnecessary and unrealistic constraint, and not fair to maintainers.
* Most importantly, I don't think the recipients of donations should be assigned on the basis of popularity. Each company should donate to those maintainers whose work it most depends on. This is something only companies can evaluate. Of course, this can become tedious or unrealistic, but I think [Thanks.dev](https://thanks.dev) is the way to solve that.

**Comment by gusaus** [comment]
Thanks for the feedback @vladh 

I should have pointed out FundOSS and Quadratic Funding is just one way Open Source Pledge participants can leverage the Open Collective platform. [This search](https://discover.opencollective.com/opensource) in particular could be a good option for companies looking to discover and fund projects they value or benefit from in a particular ecosystem or industry. 

Realizing that folks are familiar with the Open Collective platform and their team, I'm assuming they've already made a stronger case for leveraging than me! 

Quick clarification on FundOSS - 

> The point of the Open Source Pledge is for companies to donate, because they (a) have the most reason to do so, as beneficiaries of Open Source software, and (b) can afford to do so. Using QF would mean we would depend on donations from end-users as well for our system to work, and that's not fair to end-users.

Companies would donate to a match fund targeting projects, focus areas, or industries they support. While individual donations would determine how those funds are allocated, all funds would be allocated to multiple projects and maintainers.

> QF seems to work best at scale, when you have a large enough sample of donations to get a sufficient number of “votes” for every potential beneficiary. In our case, this would slow things down to the point where companies would have to wait for a sufficient number of community donations before they can make donations to many maintainers, which is an unnecessary and unrealistic constraint, and not fair to maintainers.

Again, this is just one way companies could leverage the Open Collective platform to fund open source. All contributions to a match fund would be associated with a funding round and allocated to all participants in a timely basis. 

>Most importantly, I don't think the recipients of donations should be assigned on the basis of popularity. Each company should donate to those maintainers whose work it most depends on. This is something only companies can evaluate. Of course, this can become tedious or unrealistic, but I think [Thanks.dev](https://thanks.dev/) is the way to solve that.

Thanks.dev is fantastic for identifying direct dependencies. However, in ecosystems like PHP, Drupal, or WordPress—where there are thousands of projects (plugins, themes, etc.)—using Open Collective can provide an easier, more structured way for companies to discover and fund these diverse projects, especially those indirectly supporting their operations.

Contributing to a targeted FundOSS match fund and funding round could be a compelling way for some pledge participants, while others might want to contribute to a fund where they can work with administrators of the fund to allocate. 

Hope some of the above provides a bit more clarity. As both an admin/maintainers of several projects in the ecosystem (including FundOSS), I'd love to help leverage the platform and all it has to offer.
